name: Upload to S3

on: 
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
env:
  ROOT_BUCKET_NAME: "sabahatresume.com"
  SUB_BUCKET_NAME: "www.sabahatresume.com"
  AWS_REGION : "us-east-1"
    
permissions:
  id-token: write 
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Linters
        run: npm install -g htmlhint eslint@8 stylelint stylelint-config-standard 
      
      - name: Run HTMLHint
        run: htmlhint "website/*.html"
        
      - name: Run CSS Stylelint 
        run: stylelint "website/*.css"
        
      - name: Run JavaScript Lint
        run: eslint "website/*.js"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::963527046541:role/github-actions-update-s3-static-webiste
          role-session-name: githubactions
          aws-region: ${{ env.AWS_REGION }}

        # Upload a file to AWS S3
      - name: Copy Website Code to S3
        run: |
          aws s3 cp ./website/* s3://${{ env.ROOT_BUCKET_NAME }}/
          
#      - name: Verify AWS Credentials
#        run: aws sts get-caller-identity
        
#      - uses: shallwefootball/s3-upload-action@latest
#        with:
#          aws_key_id: ${{ secrets.AWS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#          aws_bucket: ${{ secrets.AWS_BUCKET }}
#          source_dir: 'dirname'
